### ISSUE TITLE
Error parsing xml

### ISSUE THREAD

**Issue by mbeckelman** [EKibort/TeamCityFitnessePlugin#20]
I have copied the fitnesse.zip to my plugin folder and i get the following error message in my agent log;

WARN -    jetbrains.buildServer.AGENT - Failed to parse teamcity-plugin.xml from plugin: C:\BuildAgent5\plugins\Fitnesse.zip. Failed to parse plugin descriptor. Error on line 3: cvc-elt.1: Cannot find the declaration of element 'teamcity-plugin'.

**Comment by EKibort** [comment]
What version of TeamCity do you use?

**Comment by mbeckelman** [comment]
The latest version – 9.1.3. The issue has been resolved. I was putting the zip into the plugins folder, and it needed to be put into the testdata folder.

Please resolve the issue as user error  ☺

Marc Beckelman
defi SOLUTIONS
mbeckelman@defisolutions.com<mailto:mbeckelman@defisolutions.com>
425.765.1386 | defisolutions.com<http://defisolutions.com/>

**Comment by EKibort** [comment]
Thank you! :)
