### ISSUE TITLE
Teamcity

### ISSUE THREAD

**Issue by nkoradia** [EKibort/TeamCityFitnessePlugin#24]
I have compiled and copied the plugin in the  %USERPROFILE%/.BuildServer/plugins
and restarted the services teamcity server and agent
I still don't see "Fitnesse runer" while adding a build step in Teamcity
using TeamCity Professional 9.1.7 (build 37573)

**Comment by EKibort** [comment]
Please use the following manual https://confluence.jetbrains.com/display/TCD9/Installing+Additional+Plugins
