### ISSUE TITLE
Fitnesse runner step not in list

### ISSUE THREAD

**Issue by kumarvinod002** [EKibort/TeamCityFitnessePlugin#27]
hi we are restricted to add plugin to agent only. I have added agents Fitness.zip from dist in plugins of my agent but I am not able to see Fitnesse runner step in list of build steps. I can see plugin is added as per logs during restart. can you help please ?

**Comment by EKibort** [comment]
Hi 
Unfortunately it is impossible to make this plugin  agent only. 
We need to deploy several pages to server side to make it works. 
Thank you.
